[EMR][Bugfix] Fix async profile may be null and do not collect datasize of system table
```
024-03-04 14:52:23,466 WARN (starrocks-mysql-nio-pool-5|10785) [StmtExecutor.execute():643] execute Exception, sql /* ApplicationName=DBeaver 23.0.0 - SQLEditor <Script-19.sql> */ ANALYZE PROFILE FROM '3626b26a-d9f3-11ee-ac7f-7e838989e047'
java.lang.NullPointerException: null
        at com.starrocks.sql.ExplainAnalyzer.<init>(ExplainAnalyzer.java:154) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ExplainAnalyzer.analyze(ExplainAnalyzer.java:93) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleAnalyzeProfileStmt(StmtExecutor.java:1074) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:607) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:392) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:506) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:782) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2024-03-04 14:52:37,741 WARN (nioEventLoopGroup-8-4|11270) [RestBaseAction.handleRequest():86] fail to process url: /api/show_meta_info?action=SHOW_FULL_DB_SIZE
java.lang.ClassCastException: class com.starrocks.catalog.system.SystemTable cannot be cast to class com.starrocks.catalog.OlapTable (com.starrocks.catalog.system.SystemTable and com.starrocks.catalog.OlapTable are in unnamed module of loader 'app')
        at com.starrocks.http.rest.ShowMetaInfoAction.getDataSize(ShowMetaInfoAction.java:192) ~[starrocks-fe.jar:?]
        at com.starrocks.http.rest.ShowMetaInfoAction.execute(ShowMetaInfoAction.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.http.rest.RestBaseAction.handleRequest(RestBaseAction.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.http.HttpServerHandler.channelRead(HttpServerHandler.java:95) ~[starrocks-fe.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
```
Link: https://code.alibaba-inc.com/soe/starrocks/codereview/15897014
* [EMR][Bugfix] Fix async profile may be null and do not collect datasize of system table